apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-angular-app-deployment
  namespace: kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-angular-app-deployment
  template:
    metadata:
      labels:
        app: simple-angular-app-deployment
    spec:
      containers:
        - name: simple-angular-app-deployment
          image: sonyne/simple-app:vf1.0.0
          ports:
            - containerPort: 80
