apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: sonyne/simple-app:f1.0.0
          ports:
            - containerPort: 80
