apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: kube # Ensure this matches the namespace of your deploymen
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020
  type: NodePort # Or ClusterIp if you're running locally (e.g. Minikube)
  # If you're using a cloud provider, you might want to use LoadBalancer
  # type: LoadBalancer
